sonar.projectKey=AndresD902_TESTS
sonar.organization=andresd902
sonar.projectName=EmployeesAdministration Automated Tests

sonar.sourceEncoding=UTF-8

sonar.sources=auth-service,contract-service,employee-service,history-service,report-service,super-admin-service,vacation-service,e2e,performance
sonar.inclusions=**/*.ts

sonar.exclusions=node_modules/**,test-results/**,playwright-report/**,coverage/**,reports/**
sonar.coverage.exclusions=**/*.ts
